kind: Deployment
apiVersion: apps/v1
metadata:
  name: angular
  labels:
    app.kubernetes.io/name: angular
    app.kubernetes.io/part-of: microservice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: angular
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular
        app.kubernetes.io/part-of: microservice
    spec:
      containers:
        - name: angular
          image: tyeacr.azurecr.io/moviesapi:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4400

---
apiVersion: v1
kind: Service
metadata:
  name: angular
  labels:
    app.kubernetes.io/name: angular
    app.kubernetes.io/part-of: microservice
spec:
  ports:
    - port: 4400
      targetPort: 4400
  selector:
    app.kubernetes.io/name: angular